### ISSUE TITLE
change `postinstall` hook to `prepare` hook

### ISSUE THREAD

**Issue by mtiller** [mweststrate/relative-deps#16]
I'm hesitant to report this because perhaps I'm misunderstanding something.  But in the interest in at least providing feedback, here goes.

The instructions say to include a `postinstall` script that runs `relative-deps`.  But the problem I'm running into is that when I try to include my package (that has the `postinstall` script to update relative dependencies) in any other packages as a dependency, I get an error on install saying "relative-deps" is not recognzied.  So this seems to create a transitive dependency.  Or....I'm missing something?

**Comment by mweststrate** [comment]
Hmm, I think we should make sure that the postinstall hook is only run in
dev checkouts, not normal installs. There is probably an npm package that
does exactly that 😅

**Comment by mweststrate** [comment]
TY SO: https://stackoverflow.com/a/49629544. We should recommend `prepare`
instead

**Comment by mweststrate** [comment]
Updated
