### ISSUE TITLE
Support Namespaced packages

### ISSUE THREAD

**Issue by browniefed** [mweststrate/relative-deps#25]
Currently it doesn't look like it works with namespaced packages like `@abc/package`.

I don't know if just doing a recursive create would theoretically work. But I opened up a PR regardless https://github.com/mweststrate/relative-deps/pull/24

My use case is mostly focusing on using a package in development mode across web/react-native (no symlinking support).
Then we publish to github packages, and then would ignore relative-deps when we do our CI and build, etc.

**Comment by mweststrate** [comment]
Thanks for the PR! Released as 1.0.1
