### ISSUE TITLE
Add `npm` support

### ISSUE THREAD

**Issue by mweststrate** [mweststrate/relative-deps#5]
Currently only `yarn` is supported (or tested at least). `npm` would be great to have as well. 

If someone cares enough about it to make it happen :)

**Comment by elektronik2k5** [comment]
Possibly using this: https://github.com/camacho/yarn-or-npm

**Comment by rifler** [comment]
> Possibly using this: [camacho/yarn-or-npm](https://github.com/camacho/yarn-or-npm)

Great lib!

It checks installation of `yarn` or `npm` on specific computer, but I think it is more correct to check specific project.

If project top directory has `yarn.lock` - project uses `yarn` and user have to install `yarn` on his computer;
If it has `package-lock.json` - project uses `npm`;
If there is no lock file - `npm` ?

**Comment by elektronik2k5** [comment]
@rifler yeah, I think that's a better heuristic than what yarn-or-npm had last time I used it (which was over a year ago). I'd raise that issue upstream (perhaps there is such an issue already?).

**Comment by rifler** [comment]
https://github.com/camacho/yarn-or-npm/issues/4

**Comment by camacho** [comment]
A new version of the `yarn-or-npm` package (v3.0.0) just shipped. It adds support for using a project's client depending on the lockfile, and then falling back to the old behavior of checking if Yarn is installed or not.

**Comment by mweststrate** [comment]
Solved in 1.0.2
