### ISSUE TITLE
Improved path handling

### ISSUE THREAD

**Issue by mtiller** [mweststrate/relative-deps#8]
I submitted one (trivial) PR already.  I went to submit another, but realized it was a bit more involved than I had time for this instant.  But I wanted to point it out because it is a simple fix, but I just don't have time.

There are really two things that can be easily fixed.  The first is that while you import `path`, you don't use it when enough.  There are many uses of string concatenation to form file and
directory names when you really should be using `path.join(...)`.

The second issue is with `execSync`.  Specifically, you don't quote the file names.  These could
include spaces.  You'd be better off using `execFileSync`.

**Comment by mtiller** [comment]
BTW, I think without these changes, Windows will totally break.  My initial tests indicate fixing these issues should certainly improve Windows support.

**Comment by mweststrate** [comment]
PR welcome!

**Comment by mweststrate** [comment]
Should be released in 0.2.0!
